import java.util.regex.Matcher
import java.util.regex.Pattern

def projectName = new File(".").canonicalFile.name
def griffonHome = "${System.getenv("GRIFFON_HOME")}"

def griffonVersion = new File("${griffonHome}/dist/")
    .list()
    .find { it.startsWith("griffon-rt") }
    .replace("griffon-rt-", "")
    .replace(".jar", "")

def groovyVersion = new File("${griffonHome}/lib/")
    .list()
    .find { it.startsWith("groovy-sql") }
    .replace("groovy-sql-", "")
    .replace(".jar", "")

def pluginsBaseDir = "${System.getProperty('user.home')}/.griffon/${griffonVersion}/projects/${projectName}/plugins"

println "🚀 Generating build.gradle"
println ""
println "::> Project name       = $projectName"
println "::> Griffon home       = $griffonHome"
println "::> Griffon version    = $griffonVersion"
println "::> Groovy versuib     = $groovyVersion"
println "::> Pluginsd base dir  = $pluginsBaseDir"
println ""
println ""

/**
 * 1. Executa o comando Griffon para pegar o report
 */

// run griffon dependency-report runtime > dependencies-report.txt

def reportOutput = new File("./dependencies-report.txt")

println "📦 read dependencies file ${reportOutput.absolutePath}"

if(!reportOutput.exists()){
    println "::> dependencies file ${reportOutput.absolutePath} does not exists"
    return
}


// Função para remover códigos de cores ANSI (os [1;33m etc)
def cleanAnsi(String text) {
    return text.replaceAll(/\u001B\[[;?0-9]*[a-zA-Z]/, "")
}

/**
 * 3. Varredura da pasta lib local
 */
def localJars = []
def libDir = new File("lib")
if (libDir.exists()) {
    libDir.eachFileMatch(~/.*\.jar/) { file ->
        localJars << file.absolutePath.replace('\\', '/')
    }
}


def pluginJars = []
def pluginsDir = new File(pluginsBaseDir)
if (pluginsDir.exists()) {
    pluginsDir.eachFileRecurse { file ->
        if (file.name.endsWith(".jar")) {
            // Adicionamos o caminho absoluto para o IntelliJ não se perder
            pluginJars << file.absolutePath.replace('\\', '/')
        }
    }
}

/**
 * 2. Parsing das dependências
 * Regex explica: 
 * ^(\+---) : Linhas que começam com a raiz da árvore
 * \s+      : Espaço
 * ([\w\.\-]+):([\w\.\-]+):([\w\.\-]+) : Captura Group, Artifact e Version
 */
def dependencies = [] as Set
Pattern pattern = Pattern.compile(/^\+--- ([\w\.\-]+):([\w\.\-]+):([\w\.\-]+)/)

reportOutput.readLines().each { line ->
    Matcher matcher = pattern.matcher(cleanAnsi(line).trim())
    if (matcher.find()) {
        def jarName = "${matcher.group(2)}-${matcher.group(3)}.jar"
        def dep = "${matcher.group(1)}:${matcher.group(2)}:${matcher.group(3)}"

        if (pluginJars.any { it.split("/").last() == jarName }) {
            println "::> Ignore dependencie: $dep"
        } else {
            dependencies << dep
        }
    }
}

def buildFile = new File("build.gradle")
def sw = new StringWriter()
def pw = new PrintWriter(sw)

def ignore = [
    //'org.codehaus.groovy',
    //'org.apache.groovy',
    'org.codehaus.griffon.plugins',
    'griffon-rt',
    '-sources',
    '-javadoc'
]

def allDeps = []

allDeps << "\n    /// LIB JARS\n"
// Inserir JARs da pasta lib
localJars.each { jar ->
    if (ignore.any { jar.contains(it) }) {
        println "::> Ignore lib jar dependency: $jar"
    } else {
        allDeps << "    implementation files('${jar}')"
    }
}

//
allDeps << "\n\n    /// PLUGINS JARS\n"
pluginJars.each { jar ->
    if (ignore.any { jar.contains(it) }) {
        println "::> Ignore plugin jar dependency: $jar"
    } else {
        allDeps << "    implementation files('${jar}')"
    }
}

/*
allDeps << "   \n\n/// DEPENDENCIES JARS\n"
dependencies.each { dep ->

    if (ignore.any { dep.contains(it) }) {
        println "::> Ignore dependency? $dep"
    } else {
        if(dep.contains('json-lib')){
            dep = "$dep:jdk15"
        }
        allDeps << "    implementation '${dep}'"
    }
}
*/

pw.println """
// WARNING!! No change this file!!
//
// file generated on ${new Date().format('yyyy-MM-dd HH:mm:ss')}
//
// this file is generated by running `groovy idea.groovy` script
// 

plugins {
    id 'java'
    id 'groovy'
    id 'idea'
    id 'application'
    id 'com.gradleup.shadow' version '9.4.1'
}

group = 'br.com.mobilemind'
version = '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://raw.githubusercontent.com/mobilemindtech/m2/master' }
    maven { url 'https://repo1.maven.org/maven2' }
    maven { url "https://download.java.net/maven/2/" }            
    maven { url "https://mvnrepository.com/artefact" }
    maven { url "https://repository.jboss.org/nexus/content/groups/public/" }
    maven { url "https://maven.java.net/content/repositories/public/" }    
}    

dependencies {
    implementation 'org.apache.groovy:groovy-all:$groovyVersion'
    implementation 'org.codehaus.griffon:griffon-rt:$griffonVersion'

    ${allDeps.join("\n")}
}

tasks.withType(JavaCompile) {
    options.release = 25
    options.compilerArgs << '--add-opens=java.base/java.lang=ALL-UNNAMED'
}

tasks.withType(GroovyCompile) {
    groovyOptions.optimizationOptions.indy = true
}

sourceSets {
    main {
        groovy {
            // Define todas as pastas de código do Griffon como fontes do Gradle
            srcDirs = [
                'griffon-app/controllers',
                'griffon-app/models',
                'griffon-app/conf',
                'griffon-app/views',
                'griffon-app/services',
                'griffon-app/lifecycle',
                'src/main/java',
                'src/main/groovy',
                //'scripts'
            ]
        }
        resources {
            // Define onde ficam os arquivos de configuração, i18n e imagens
            srcDirs = [
                'griffon-app/resources',
                'griffon-app/i18n',
                'griffon-app/conf',
                'src/resources'
            ]
        }
    }
    test {
        groovy {
            srcDirs = ['test/unit', 'test/integration']
        }
        resources {
            srcDirs = ['test/resources']
        }
    }
}

// Configuração do Plugin Application (Para rodar em modo Dev)
application {
    mainClass = 'griffon.swing.SwingApplication' // Ou a sua classe main customizada
}

run {
    systemProperty 'griffon.env', 'dev'
    workingDir = rootProject.projectDir
    standardInput = System.in
    
    jvmArgs = [
        '--add-opens=java.base/java.lang=ALL-UNNAMED',
        '--add-opens=java.base/java.util=ALL-UNNAMED'
    ]
}

shadowJar {
    archiveClassifier.set('dist')
    
    // CORREÇÃO DAS EXTENSÕES: Mescla os arquivos do Groovy 6 automaticamente!
    mergeServiceFiles {
        include 'META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule'
    }
}
"""

buildFile.text = sw.toString()

println "--------------------------------------------------------"
println "📊 Dependencies: ${dependencies.size()}"
println "📁 LIB jars: ${localJars.size()}"
println "📁 Plugins jars: ${pluginJars.size()}"
println "✅ 'build.gradle' generated successfully!"
println "--------------------------------------------------------"