import java.text.SimpleDateFormat

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }

    dependencies {
        classpath 'org.codehaus.griffon:griffon-gradle-plugin:${griffonVersion}'
    }
}

apply plugin: 'groovy'
apply plugin: 'org.codehaus.griffon.project'

Date buildTimeAndDate = new Date()
ext {
    buildDate = new SimpleDateFormat('yyyy-MM-dd').format(buildTimeAndDate)
    buildTime = new SimpleDateFormat('HH:mm:ss.SSSZ').format(buildTimeAndDate)
    buildVersion = "${new Date().time}"
    macosx = System.getProperty('os.name').contains('Mac OS')
}

griffon {
    disableDependencyResolution = false
    includeGroovyDependencies = true
    version = '${griffonVersion}'
    toolkit = 'swing'
    applicationProperties = [
        'build_date'    : buildDate,
        'build_time'    : buildTime,
        'build_revision': buildVersion
    ]
}

mainClassName = '${package}.Launcher'

apply from: 'gradle/publishing.gradle'

dependencies {
    api "org.codehaus.griffon:griffon-guice:${griffon.version.get()}"

    runtimeOnly "org.slf4j:slf4j-simple:${slf4jVersion}"

    testImplementation "org.codehaus.griffon:griffon-swing-test:${griffon.version.get()}"
    testImplementation("org.spockframework:spock-core:${spockVersion}"){
        exclude group: 'org.apache.groovy'
        exclude group: 'org.junit'
    }
    testImplementation("org.hamcrest:hamcrest:${hamcrestVersion}")
    testImplementation("org.awaitility:awaitility-groovy:${awaitilityVersion}")
    testImplementation("org.apache.groovy:groovy-all:${groovyVersion}"){
        exclude group: 'junit', module: 'junit'
        exclude group: 'org.apache.groovy', module: 'groovy-test-junit5'
    }
}

configurations.all {
    resolutionStrategy {
        force "org.apache.groovy:groovy:${groovyVersion}"
        force "org.apache.groovy:groovy:${groovyVersion}"
        force "org.hamcrest:hamcrest:${hamcrestVersion}"
    }
}

startScripts {
    doLast {
        if (!macosx) unixScript.text = unixScript.text.replaceAll('"(-Xdock:(name|icon)=)([^"]*?)(")', ' ')
        windowsScript.text = windowsScript.text.replaceAll('"(-Xdock:(name|icon)=)([^"]*?)(")', ' ')
    }
}

if (hasProperty('debugRun') && ((project.debugRun as boolean))) {
    run {
        jvmArgs '-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005'
    }
}