griffonVersion=${griffonVersion}
groovyVersion=${groovyVersion}
log4jVersion=${log4jVersion}
slf4jVersion=${slf4jVersion}
slf4jReload4jVersion=${slf4jReload4jVersion}
reload4jVersion=${reload4jVersion}