griffon.version=@version@
groovy.version=@groovyVersion@
ant.version=@antVersion@
slf4j.version=@slf4jVersion@
slf4j.reload4j.version=@slf4jReload4jVersion@
reload4j.version=@reload4jVersion@
log4j.version=@log4jVersion@
spring.version=@springVersion@
junit.version=@junitVersion@